---
# tasks file for roles/startup

- name: Signal Node-A to Start
  debug:
    msg: ''
  changed_when: true
  notify: Start_Node_A
  tags:
    - node-a

- name: Signal Node-B to Start
  debug:
    msg: ''
  changed_when: true
  notify: Start_Node_B
  tags:
    - node-b

- name: Signal Node-C to Start
  debug:
    msg: ''
  changed_when: true
  notify: Start_Node_C
  tags:
    - node-c
