program:
  folder_path: "/home/gig/local_repos/tdarr-node-switcher/tdarr-noding"
tdarr_server:
  url: "http://192.168.51.30:8265"
  api_string: "/api/v2"
  max_nodes: 4
  default_priority_level: 2
tdarr_nodes:
  ganosLal:
    primary_node: true
    priority: 0
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 3
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 2
      min_gpu: 0
      max_gpu: 3
  server-node:
    priority: 3
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 6
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-a:
    priority: 1
    startup_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/startup.yml --skip-tags \"node-b\",\"node-c\""
    shutdown_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/shutdown.yml --skip-tags \"node-b\",\"node-c\""
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 6
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-b:
    priority: 2
    startup_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/startup.yml --skip-tags \"node-a\",\"node-c\""
    shutdown_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/shutdown.yml --skip-tags \"node-a\",\"node-c\""
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 6
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-c:
    priority: 4
    startup_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/startup.yml --skip-tags \"node-a\",\"node-b\""
    shutdown_cmd: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible playbook /home/gig/local_repos/tdarr-node-switcher/ansible_files/shutdown.yml --skip-tags \"node-a\",\"node-b\""
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 6
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
