program:
  folder_path: "/home/gig/local_repos/tdarr-node-switcher/tdarr-noding"
  ansible_path: "/home/gig/local_repos/tdarr-node-switcher/ansible_files"
tdarr_server:
  url: "http://192.168.51.30:8265"
  api_string: "/api/v2"
  max_nodes: 4
  default_priority_level: 1
tdarr_nodes:
  ganosLal:
    primary_node: true
    priority: 0
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 3
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 2
      min_gpu: 0
      max_gpu: 3
  server-node:
    priority: 1
    startup_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook server_node_startup.yml"
    shutdown_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook server_node_shutdown.yml"
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-a:
    priority: 2
    startup_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook startup-node-a.yml"
    shutdown_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook shutdown-node-a.yml"
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-b:
    priority: 3
    startup_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook startup-node-b.yml"
    shutdown_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook shutdown-node-b.yml"
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
  node-c:
    priority: 4
    startup_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook startup-node-c.yml"
    shutdown_command: "/home/gig/local_repos/tdarr-node-switcher/.venv/bin/ansible-playbook shutdown-node-c.yml"
    healthcheck_worker_limits:
      min_cpu: 0
      max_cpu: 5
      min_gpu: 0
      max_gpu: 0
    transcode_worker_limits:
      min_cpu: 0
      max_cpu: 3
      min_gpu: 0
      max_gpu: 0
